import { prisma } from '../db/client.js';

export const AuditEvents = {
  REGIONAL_ALLOCATION_CREATED: 'REGIONAL_ALLOCATION_CREATED',
  PROJECT_SCORED: 'PROJECT_SCORED',
  ALLOCATION_PROPOSED: 'ALLOCATION_PROPOSED',
  ALLOCATION_APPROVED: 'ALLOCATION_APPROVED',
  ALLOCATION_REJECTED: 'ALLOCATION_REJECTED',
  PROJECT_FUNDED: 'PROJECT_FUNDED',
  SIMULATION_ADVANCED: 'SIMULATION_ADVANCED',
  MILESTONE_COMPLETED: 'MILESTONE_COMPLETED',
  MILESTONE_MISSED: 'MILESTONE_MISSED',
  MILESTONE_PAUSED_EXTERNAL: 'MILESTONE_PAUSED_EXTERNAL',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  EVIDENCE_REVIEWED: 'EVIDENCE_REVIEWED',
  SALVAGE_EVALUATED: 'SALVAGE_EVALUATED',
  REALLOCATION_PROPOSED: 'REALLOCATION_PROPOSED',
  REALLOCATION_APPROVED: 'REALLOCATION_APPROVED',
  REALLOCATION_REJECTED: 'REALLOCATION_REJECTED',
  DEMO_RESET: 'DEMO_RESET',
  DATA_IMPORTED: 'DATA_IMPORTED',
  PROPOSAL_SUBMITTED: 'PROPOSAL_SUBMITTED',
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
} as const;

export type AuditEventName = (typeof AuditEvents)[keyof typeof AuditEvents];

export async function logAudit(event: AuditEventName, details: string, actor = 'CSR Administrator') {
  return prisma.auditEvent.create({
    data: { event, details, actor },
  });
}
